apiVersion: 1

datasources:

  - name: ClothFlow-Prometheus
    uid: clothflow-prometheus

    type: prometheus
    access: proxy

    url: http://${PROMETHEUS_SERVICE_HOST}:9090

    isDefault: true
    editable: false

    jsonData:
      httpMethod: POST
      manageAlerts: true